/** Conversation controls and feedback; keys follow the pinned upstream dictionary. */
export const conversation = {
  'hint.plan': 'کار خود را شرح دهید تا برنامهٔ انجام آن تهیه شود',
  'hint.goal': 'هدف یک کار طولانی‌مدت را شرح دهید',
  'hint.goal.active': 'هدف فعال است — ویرایش / مکث / ادامه / پاک کردن',
  'placeholder.plan': 'کار خود را شرح دهید تا برنامهٔ انجام آن تهیه شود',
  'placeholder.default': 'پیام بنویسید یا کاری اجرا کنید؛ / برای دستورها، @ برای فایل‌ها یا نشست‌ها',
  'placeholder.unavailable': 'نشست در دسترس نیست',
  'placeholder.parentOffline': 'نشست والد آفلاین است؛ ارسال ممکن نیست، اما همچنان می‌توانید اجرا را متوقف کنید',
  'placeholder.hero': 'آنچه می‌خواهید بسازید را شرح دهید؛ / برای دستورها، @ برای فایل‌ها یا نشست‌ها',
  'placeholder.workspace': 'برای شروع، یک فضای کاری انتخاب کنید',
  'placeholder.steerQueue': 'با Cmd/Ctrl+Enter همهٔ پیام‌های صف را برای هدایت اجرای جاری بفرستید',
  'input.commands': 'افزودن فایل یا اجرای دستور',
  'input.file': 'فایل',
  'input.stop': 'توقف تولید پاسخ',
  'input.send': 'ارسال پیام',
  'input.send.queue': 'افزودن پیام به صف',
  'input.send.steer': 'هدایت اجرای جاری با پیام',
  'attachment.pending': 'پیوست‌های در انتظار',
  'attachment.scrollLeft': 'پیمایش پیوست‌ها به چپ',
  'attachment.scrollRight': 'پیمایش پیوست‌ها به راست',
  'attachment.dropTitle': 'برای افزودن فایل یا تصویر، آن را اینجا بکشید',
  'attachment.dropDesc': 'محدودیت تصویر: حداکثر {count} تصویر، هر کدام {size}',
  'attachment.dropBlocked': 'در حال حاضر افزودن فایل و تصویر ممکن نیست',
  'image.pending': 'تصاویر در انتظار',
  'image.openOriginal': 'نمایش تصویر اصلی',
  'image.openOriginalLabel': '{label}، برای نمایش تصویر اصلی کلیک کنید',
  'image.remove': 'حذف تصویر {name}',
  'image.original': 'تصویر اصلی',
  'image.label': 'تصویر',
  'image.loadFailed': 'بارگذاری تصویر ناموفق بود؛ برای تلاش دوباره کلیک کنید',
  'image.loading': 'در حال بارگذاری تصویر…',
  'image.preview': 'پیش‌نمایش تصویر اصلی',
  'image.closePreview': 'بستن پیش‌نمایش تصویر اصلی',
  'image.unsupportedType': 'فقط تصاویر PNG، JPG، WebP و GIF پشتیبانی می‌شوند',
  'image.tooMany': 'هر پیام می‌تواند حداکثر {count} تصویر داشته باشد',
  'image.fileTooLarge': 'اندازهٔ هر تصویر باید کمتر از {size} باشد',
  'image.totalTooLarge': 'اندازهٔ مجموع تصاویر از {size} بیشتر است؛ تعدادی را حذف و دوباره تلاش کنید',
  'image.tooManyPixels': 'وضوح تصویر بیش از حد بالاست؛ آن را فشرده و دوباره تلاش کنید',
  'image.dimensionTooLarge': 'هر ضلع تصویر باید حداکثر {size} پیکسل باشد؛ ابعاد را کاهش دهید و دوباره تلاش کنید',
  'image.modelUnsupported': 'مدل فعلی از تصویر پشتیبانی نمی‌کند؛ مدلی با پشتیبانی تصویر انتخاب کنید',
  'image.sendFailed': 'ارسال تصاویر ناموفق بود ({reason})؛ دوباره آن‌ها را اضافه و تلاش کنید',
  'file.pending': 'فایل‌های در انتظار',
  'file.remove': 'حذف فایل {name}',
  'file.uploading': 'در حال بارگذاری…',
  'file.uploadFailed': 'بارگذاری ناموفق بود؛ برای تلاش دوباره کلیک کنید',
  'file.retry': 'تلاش دوباره برای بارگذاری {name}',
  'file.stillUploading': 'فایل‌ها هنوز در حال بارگذاری‌اند؛ پس از پایان بارگذاری ارسال کنید',
  'file.sessionUnavailable': 'نشست در دسترس نیست؛ بارگذاری فایل ممکن نیست',
  'file.notStaged': 'بارگذاری فایل تمام نشده است؛ دوباره آن را اضافه و تلاش کنید',
  'file.label': 'فایل',
  'context.aria': '{percent} از ظرفیت زمینه استفاده شده است',
  'context.used': 'از ظرفیت زمینه استفاده شده',
  'context.system': 'دستور سیستم',
  'context.tools': 'تعریف ابزارها',
  'context.messages': 'پیام‌ها',
  'settings.enter.title': 'رفتار ارسال هنگام اجرای کار',
  'settings.enter.description': 'عملکرد Enter و دکمهٔ ارسال هنگام اجرای عامل؛ Cmd/Ctrl+Enter رفتار دیگر را اجرا می‌کند',
  'settings.enter.queue': 'افزودن به صف',
  'settings.enter.steer': 'هدایت اجرای جاری',
  'hero.headline': 'به سوی ناشناخته‌ها',
  'hero.preview': 'پیش‌نمایش',
  'hero.chooseWorkspace': 'انتخاب فضای کاری',
  'session.hierarchy': 'سلسله‌مراتب نشست‌ها',
  'todo.title': 'کارهای پیش رو',
  'todo.progress.done': '{done} مورد انجام شده',
  'todo.progress.active': '{active} مورد در حال انجام',
  'todo.progress.pending': '{pending} مورد در انتظار',
  'todo.rowTitle': 'به‌روزرسانی فهرست کارها',
  'todo.completed': '{done} از {total} مورد انجام شده',
  'command.attachmentsUnsupported': '/{command} پیوست نمی‌پذیرد؛ ابتدا پیوست‌ها را حذف کنید',
  'ask.rowTitle': 'پرسیدن سؤال',
  'ask.waiting': 'در انتظار',
  'ask.cancelled': 'لغو شده',
  'ask.cancelledDetail': 'این مجموعه سؤال پیش از ارسال پاسخ‌ها لغو شد.',
  'ask.interrupted': 'متوقف شده',
  'ask.interruptedDetail': 'این مجموعه سؤال پیش از ارسال پاسخ‌ها متوقف شد.',
  'ask.answered': '{answered} از {total} سؤال پاسخ داده شده',
  'ask.skipped': 'پاسخ داده نشده',
  'bash.running': 'در حال اجرا',
  'bash.failed': 'ناموفق',
  'bash.stopped': 'متوقف شده',
  'row.running': 'در حال اجرا',
  'row.failed': 'ناموفق',
  'row.stopped': 'متوقف شده',
  'row.input': 'ورودی',
  'row.output': 'خروجی',
  'row.inspect': 'بررسی',
  'tool.title.search': 'جست‌وجو',
  'tool.title.read': 'خواندن',
  'tool.title.bash': 'Bash',
  'tool.title.write': 'نوشتن',
  'tool.title.edit': 'ویرایش',
  'tool.title.code': 'کد',
  'tool.title.generic': 'فراخوانی ابزار',
  'tool.title.inspect': 'بررسی',
  'tool.title.runCordis': 'اجرای افزونهٔ Cordis',
  'tool.title.stopCordis': 'توقف افزونهٔ Cordis',
  'tool.title.removeCordis': 'حذف افزونهٔ Cordis',
  'tool.title.pwsh': 'Pwsh',
  'tool.title.readImage': 'خواندن تصویر',
  'tool.title.grep': 'Grep',
  'tool.title.glob': 'Glob',
  'tool.title.webSearch': 'جست‌وجو',
  'tool.title.webFetch': 'دریافت',
  'tool.autoReviewRejected': 'بررسی خودکار آن را رد کرد',
  'tool.autoReviewNotExecuted': 'ابزار اجرا نشد. دلیل: {reason}',
  'tool.autoReviewReasonFallback': 'بررسی خودکار به این اقدام اجازه نداد',
  'diff.files.one': '{count} فایل',
  'diff.files.other': '{count} فایل',
  'diff.collapseAria': 'جمع کردن تفاوت‌ها',
  'diff.expandAria': 'نمایش {count} خط دیگر از تفاوت‌ها',
  'diff.expandRest': '… {count} خط دیگر',
  'read.window': 'نمایش {shown} خط از {total} خط',
  'read.collapseAria': 'جمع کردن محتوا',
  'read.expandAria': 'نمایش {count} خط دیگر',
  'read.expandRest': '… {count} خط دیگر',
  'search.paths': '{shown} مسیر',
  'search.paths.truncated': 'نمایش {shown} مسیر از {total} مسیر',
  'search.matches': '{shown} نتیجه در {files} فایل',
  'search.matches.truncated': 'نمایش {shown} نتیجه از {total} نتیجه در {files} فایل',
  'search.noResults': 'نتیجه‌ای یافت نشد',
  'search.collapseAria': 'جمع کردن نتایج',
  'search.expandAria': 'نمایش {count} خط دیگر از نتایج',
  'search.expandRest': '… {count} خط دیگر',
  'web.noResults': 'نتیجه‌ای یافت نشد',
  'web.sourcesTruncated': 'فهرست منابع کوتاه شده است',
  'web.http': 'HTTP',
  'web.contentTruncated': 'محتوا کوتاه شده است',
  'details.running': 'در حال اجرا…',
  'queue.count': '{n} پیام در صف',
  'queue.sending': 'در حال ارسال…',
  'queue.image': 'تصویر پیام در صف',
  'queue.file': 'فایل در صف {name}',
  'queue.edit': 'ویرایش پیام در صف',
  'queue.edit.unsupported': 'محتوای غیرمتنی دارد؛ ویرایش هنوز پشتیبانی نمی‌شود',
  'queue.save': 'ذخیرهٔ پیام در صف',
  'queue.cancelEdit': 'لغو ویرایش',
  'queue.remove': 'حذف پیام از صف',
  'queue.steer': 'هدایت اجرای جاری با پیام در صف',
  'queue.steer.unavailable': 'هدایت اجرا فقط هنگام اجرای عامل در دسترس است',
  'error.sessionInUse': 'این نشست از قبل در حال استفاده است؛ احتمالاً در نمونهٔ دیگری از DSH (مانند dsh web یا برنامهٔ دسکتاپ). نمونه‌های دیگر DSH را ببندید و دوباره تلاش کنید.',
  'queue.editFailed': 'ویرایش ناموفق بود؛ ممکن است ارسال این پیام شروع شده باشد.',
  'queue.removeFailed': 'حذف ناموفق بود؛ ممکن است ارسال این پیام شروع شده باشد.',
  'queue.steerFailed': 'هدایت اجرا ناموفق بود. دوباره تلاش کنید.',
  'terminal.signal': 'سیگنال {signal}',
  'terminal.exitCode': 'کد خروج {code}',
  'terminal.noExitCode': 'کد خروج موجود نیست',
  'terminal.running': 'در حال اجرا',
  'terminal.failed': 'ناموفق',
  'terminal.done': 'انجام شد',
  'terminal.noOutput': 'خروجی ندارد',
  'terminal.collapseAria': 'جمع کردن خروجی',
  'terminal.expandAria': 'نمایش {n} خط باقی‌ماندهٔ خروجی',
  'terminal.expandRest': '… {n} خط دیگر',
  'terminal.sendInput': '(ارسال ورودی)',
  'terminal.session': 'ترمینال {sessionId}',
};
